# -*- coding: utf-8 -*-
"""fake_news_gpt3_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DGtAHo9Koxt2a48RMJMLPKlBrMfOYywF
"""

#imports 
#get summary  of news 
#

#installations 
# !pip install nltk 
# !pip install newspaper3k 
# !pip install openai

import nltk
from newspaper import Article 
import openai
import nltk

nltk.download('punkt')

def get_summary(url):
    article=Article(url)
    article.download()
    article.parse()
    article.nlp()
    article_summary=article.summary 
    return article_summary 

def gpt3(text):
    openai.api_key='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'
    response = openai.Completion.create(
    model="text-davinci-003",
    prompt=text,
    temperature=0.7,
    max_tokens=2000,
    top_p=1.0,
    frequency_penalty=0.0,
    presence_penalty=1
    )
    content=response.choices[0].text
    print(content)
    return response.choices[0].text

def fact_check(text_peice):
    topic=text_peice
    # query1="check if this is fake news "+topic+" and cite if sources with links if it is and if it is not fake"
    
    # query2="fact check this statement with statistics and official goverment sources "+topic+"and also provide other sources with links"
    query1=f"Based on the email header provided {topic} detect what email fraud it is .in a single word tell if it is spam or not and give the category of spam . Give the ip address of the sender and the location of that ip"
    # query2="in a single word tell if it is spam or not and give the category of spam . Give the ip address of the sender and the location of that ip"
    gpt3(query1)
    # gpt3(query2)

fact_check(get_summary("https://www.inquirer.com/opinion/commentary/republicans-tennessee-expulsion-anti-democracy-20230409.html"))

